# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import fileup.llmodels.homewore_courseware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homewore_Courseware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=40)),
                ('classname', models.CharField(max_length=40)),
                ('homework', models.FileField(upload_to=fileup.llmodels.homewore_courseware.get_file_path)),
            ],
        ),
    ]
